courses = ['Maths','Science','Tech']

print(courses)
print(len(courses))
print(courses[0])
print(courses[2])
print(courses[-1])
print(courses[0:2]) #2 is exclusive
courses.append('History')
print(courses)
courses.insert(0,'Geography')
print(courses)
courses.extend(['Art','Music'])
print(courses)
courses.remove('Tech')
print(courses)
courses.pop()
print(courses)
courses.reverse()
print(courses)
courses.sort()
print(courses)
courses.sort(reverse=True)
print(courses)
print(min(courses))
print(max(courses))
print(courses.index('Maths'))
print('Maths' in courses)

course_str = ', '.join(courses)
print(course_str)